name: Verify Checklist

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  verify_checklist:
    name: Verify Checklist
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract checklist items
        id: extract
        run: |
          echo "::set-output name=checklist::$(echo "${{ github.event.pull_request.body }}" | grep -o '\[ \]')"

      - name: Verify Checklist
        run: |
          checklist="${{ steps.extract.outputs.checklist }}"
          if [ -z "$checklist" ]; then
            echo "$checklist Not all checkboxes are checked."
            exit 1
          else
            echo "$checklist All checkboxes are checked."
          fi
