name: Check Pull Request Template

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check_template:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if PR template has all checkmarks
        run: |
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_HTML=$(curl -s "$PR_URL")
          
          if echo "$PR_HTML" | grep -q '<input[^>]*type="checkbox"[^>]*\s+unchecked>'; then
            echo "Some checkmarks are missing in the pull request window."
            exit 1
          else
            echo "All checkmarks present in the pull request window."
            exit 0
          fi
