name: Pull Request Template Check

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check_pull_request_template:
    name: Check Pull Request Template
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if Pull Request Template is complete
        run: |
          template_path=$(<PULL_REQUEST_TEMPLATE.md)
          if sed -n '[ ]' "$template_path"; then
            echo "Some checkmarks are missing in pull request template."
            exit 1
          else
            echo "All checkmarks present in pull request template."
            exit 0
          fi 
